export const NUMBER_FACT_REQUEST = 'NUMBER_FACT_REQUEST';
export const NUMBER_FACT_RECEIVE = 'NUMBER_FACT_RECEIVE';
export const NUMBER_FACT_ERROR = 'NUMBER_FACT_ERROR';
export const NUMBER_COUNTER_ADD = 'NUMBER_COUNTER_ADD';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY';
export const SCREEN_RESIZE = 'SCREEN_RESIZE';
